[package]
name = "netlink"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
libc = "0.2.147"
serde = { version = "1.0.188", features = ["derive"] }
