[package]
name = "wgctrl"
version = "0.0.1"
edition = "2021"
license = "MIT"
description = "wgctrl is a crate that enables control over wireguard interfaces"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
